# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jod2yDKtMwCP98AqLOP8LCS0aWihL77U
"""

!git clone https://github.com/NidhiAI/Speaker-Recognition-GMM

!pip install python_speech_features

pwd

cd '/content/Speaker-Recognition-GMM'

pwd

!python FeatureExtraction.py

!python TrainingModel.py

!python Test.py

!pip install ffmpeg-python

# for testing 
file_name = input('Enter your name: ')
print(f'You entered {file_name}')

# Now record your voice



!python RecordAudio

filename = 'felixtest.wav'
record(filename, 5)

import IPython
IPython.display.Audio(filename)