# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wWwfW9yNnPSNakcMo9BdXrdkdXbP8suk
"""

import pandas as pd
data = pd.read_csv('/content/Speaker-Recognition-GMM/maleFemale/librosa.csv')
data.head() # Display 5 wav files features 

data.label.unique()

data.label.value_counts()

# Dropping unneccesary columns 'filename'
data = data.drop(['filename'],axis=1)#Encoding the Labels